### ISSUE TITLE
Add Docker development environment

### ISSUE THREAD

**Issue by jamesh38** [usetrmnl/byos_hanami#134]
Continuing our discussion from closed PR 

> That said, I do want help kick this off so here's some thoughts: 

> To get you up to speed, in case you need more context and haven't read through the Git history, Dev Container support was added in the first commit and then was removed in this commit which explains the reasoning why.
> * I've been thinking about this more since we last discussed this and am wondering if we could lean into Dockerfile build stages (as you show in your code with a dev stage) and via compose.yml where the Docker image is dynamically built based on environment variables so folks could easily use a single script with an argument. 
> * For example, here's my Dotfiles Overmind Bash Function for when I need to toggle between development and production mode when running locally (pure Ruby stack, not Docker). This would eliminate the need to maintain multiple files and reduce duplication while hopefully not introducing too much conditional logic?

Thanks I wasn't aware there was an early push for a devcontainer setup will review the reasoning for removing.

Let me review what you had mentioned here and see if I understand what you're looking for. If this is too large a contribution for a newcomer like myself as well then no worries.

**Comment by bkuhlmann** [comment]
Thanks, yeah, I think this is a worthwhile endeavor so if you want to dig into this, I think that's great. I think there are two avenues of attack:

- **Dev Containers**: What you are proposing but does require using VS Code/GitHub.
- **Reusable Docker file/compose Configuration**: This would allow folks to use pure Docker with any tooling.

Maybe we need to support both but I'm not sure. Having a reusable Docker configuration that can build for development and production feels like the most flexible solution in my mind but open to suggestions. Do you know of other projects that have tackled this problem and solved it well? Maybe we need to study examples first?

**Comment by jamesh38** [comment]
Sorry for the delay, Brooke. I think a simple `compose.yml` file combined with a dedicated `development` stage in the Dockerfile might be our best approach. This avoids the complexity and VS Code/devcontainers requirement, allowing a wider audience to use the tooling easily.

While I don’t use it as much anymore, the Laravel ecosystem has an exceptionally ergonomic developer experience—specifically through a tool called [Laravel Sail](https://laravel.com/docs/12.x/sail). Sail generates and manages an optimized Docker environment for your Laravel application. In the linked repository, you can see [Dockerfiles](https://github.com/laravel/sail/tree/1.x/runtimes) for different PHP versions and [service stubs](https://github.com/laravel/sail/tree/1.x/stubs) for Redis, MySQL, Postgres, etc. I’m not suggesting we replicate everything Sail provides, but it can serve as a clear guide for key parts of the developer experience we care about.

Below are the snippets for a Laravel app and Postgres service from a Sail-generated `docker-compose.yml` (after running `./vendor/bin/sail up` on a fresh Laravel install):

### Laravel App

```yaml
laravel.test:
  build:
    context: './vendor/laravel/sail/runtimes/8.4'
    dockerfile: Dockerfile
    args:
      WWWGROUP: '${WWWGROUP}'
  image: 'sail-8.4/app'
  extra_hosts:
    - 'host.docker.internal:host-gateway'
  ports:
    - '${APP_PORT:-80}:80'
    - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
  environment:
    WWWUSER: '${WWWUSER}'
    LARAVEL_SAIL: 1
    XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    IGNITION_LOCAL_SITES_PATH: '${PWD}'
  volumes:
    - '.:/var/www/html'
  networks:
    - sail
  depends_on:
    - pgsql
    - redis
```

### Postgres

```yaml
pgsql:
  image: 'postgres:17'
  ports:
    - '${FORWARD_DB_PORT:-5432}:5432'
  environment:
    PGPASSWORD: '${DB_PASSWORD:-secret}'
    POSTGRES_DB: '${DB_DATABASE}'
    POSTGRES_USER: '${DB_USERNAME}'
    POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
  volumes:
    - 'sail-pgsql:/var/lib/postgresql/data'
    - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
  networks:
    - sail
  healthcheck:
    test:
      - CMD
      - pg_isready
      - '-q'
      - '-d'
      - '${DB_DATABASE}'
      - '-U'
      - '${DB_USERNAME}'
    retries: 3
    timeout: 5s
```

And here are the network and volume definitions:

```yaml
networks:
  sail:
    driver: bridge

volumes:
  sail-pgsql:
    driver: local
  sail-redis:
    driver: local
```

---

#### Key Takeaways

* **Build args**
  Pass in values like `WWWGROUP` so the container’s permissions match the host user.

* **Environment variables (backed by sensible defaults)**
  Let people override settings like ports (`APP_PORT`, `VITE_PORT`) or credentials (`DB_USERNAME`, `DB_PASSWORD`) via `.env`.

* **Volumes for persistent code + data**

  * Code: `.:/var/www/html` keeps your working directory in sync.
  * Data: Named volume `sail-pgsql` ensures Postgres data persists across restarts.

* **Volume driver specification**

* **Dedicated network**
  Isolates container traffic (e.g., bridge network named `sail`), which improves reliability and service discovery.

* **Container dependencies**
  `depends_on: [pgsql, redis]` ensures the database/Redis start before the app. We might also want a simple retry script in the entrypoint to handle “service is still starting” errors.

* **Configurable port exposures**
  Map container ports to host ports using environment variables so people can run multiple projects without conflicts.

* **Health checks**
  Postgres’s `pg_isready` to confirm the database is accepting connections before the app tries to connect.

* **`.env` file support**
  Encourage a shared `.env.example` and `.env` workflow so everyone has the same baseline environment configuration.

* **Logging/Debug**
  Consider mounting a log directory or forwarding logs to stdout/stderr so developers can easily inspect logs without `docker exec`.

* **Restart policies**
  For development, we might not need this, but in production it can help (e.g., `restart: on-failure`).

* **Service user mapping**
  Match container UID/GID to the host user for file permissions (Laravel Sail handles this with `WWWUSER`/`WWWGROUP`).

---

All that being said, this feels like a solid starting point. A few basic questions for you:

1. **Is a secondary compose file acceptable?**
   (e.g., `compose.yml` for production and `compose.dev.yml` for local development)

2. **Is modifying the Dockerfile minimally to add a `development` stage acceptable?**
   (Similar to my closed PR—just add a small stage that installs dev dependencies)

3. **Should we back these up with scripts in `bin/` (e.g., `bin/start-dev` or `bin/start-prod`)?**
   That way running `./bin/start-dev` or `./bin/start-prod` abstracts away the `docker-compose` flags from the developer. Or using env vars as you suggested with your personal dotfile command.

Let me know your thoughts, and we can refine this further.
