### ISSUE TITLE
Fix Puma and Docker port configuration

### ISSUE THREAD

**Issue by hossain-khan** [usetrmnl/byos_hanami#164]
When I use docker compose env config with port other than `2300` it's not able to forward to the internal application port. Potentially bcause of current config:

```yml
    ports:
      - "${APP_PORT}:${APP_PORT}"
```

Ideally it should be 

```yml
    ports:
      - "${APP_PORT}:2300"
```

However, based on AI research, it mentioned that adding missing `HANAMI_PORT` should also fix this issue. For example:

```yml
    environment:
      API_URI: ${API_URI}
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@database:5432/${PG_DATABASE}
      BUNDLE_DEPLOYMENT: 0
      BUNDLE_FROZEN: "false"
      HANAMI_PORT: ${APP_PORT}
```

### Summary of the Issue and Fix

**Issue Identified**: 
- Your application listens on port 2300 inside the container (defined in puma.rb)
- Your Docker Compose configuration was mapping port 2355 to 2355, but nothing was listening on port 2355 inside the container

**Solution Applied**: 
Option 2 (Adding HANAMI_PORT environment variable)
- Added the environment variable `HANAMI_PORT: ${APP_PORT}` to both Docker Compose files
- Kept the port mapping as `"${APP_PORT}:${APP_PORT}"` (2355:2355)

This ensures that Puma will listen on the same port inside the container that you're mapping to on the host. Now when you access http://localhost:2355, it will correctly reach your application.

---

Problem details

1. In puma.rb, the application is configured to listen on the port specified by the environment variable `HANAMI_PORT` or defaults to port `2300` if that variable is not set:
   ```ruby
   port ENV.fetch "HANAMI_PORT", 2300
   ```

2. In your Dockerfile, the container exposes port 2300:
   ```Dockerfile
   EXPOSE 2300
   ```

3. Your .env file sets `APP_PORT=2355`, but there's no direct connection between `APP_PORT` and `HANAMI_PORT`.

4. The Docker Compose configuration maps `${APP_PORT}:${APP_PORT}` (2355:2355), but your application is actually listening on port 2300 inside the container.

**This confirms that your current configuration is incorrect**. The application is listening on port 2300 inside the container, but you're trying to map to port 2355.
